name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Boost dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libboost-all-dev 
    - name: Compile 
      run: cd src && make
